version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn -w=4 -b=0.0.0.0:5000 index:app
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
